import * as XLSX from 'xlsx';
import { Contact, ValidatedImportRecord } from '../types';

export const EMAIL_REGEX = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)+$/;
export const PHONE_REGEX = /^[=]?['"]?\+?[0-9\s\-().]{7,25}['"]?$/;

export interface ColumnMappingConfig {
  nameCol?: number;
  firstNameCol?: number;
  lastNameCol?: number;
  emailCol?: number;
  phoneCol?: number;
  companyCol?: number;
  tagsCol?: number;
}

export interface AvailableColumn {
  index: number;
  label: string;
  sample?: string;
}

export interface ParseExcelOptions {
  sheetName?: string;
  headerRowIndex?: number;
  columnMapping?: ColumnMappingConfig;
  allowPhoneOnly?: boolean;
}

export interface ParseExcelResult {
  records: ValidatedImportRecord[];
  validCount: number;
  invalidCount: number;
  duplicateCount: number;
  existingDuplicateCount: number;
  phoneOnlyCount: number;
  availableSheets: string[];
  activeSheetName: string;
  headerRowIndex: number;
  availableColumns: AvailableColumn[];
  mappedColumns: {
    nameCol: number;
    emailCol: number;
    phoneCol: number;
    companyCol: number;
    tagsCol: number;
  };
  totalRawRows: number;
}

/**
 * Normalizes phone numbers by handling scientific notation, Excel formula prefixes (=, ="),
 * trailing decimals (.0), Indian formats (+91, =91, 91, 0, 10-digit), and E.164 international numbers.
 */
export function normalizePhone(phone: any): string {
  if (phone === null || phone === undefined) return '';
  let str = String(phone).trim();
  if (!str) return '';

  // Handle scientific notation e.g. 9.87654E+11 or 9.87654e+09 commonly generated by Excel for numbers
  if (str.includes('e+') || str.includes('E+')) {
    const n = Number(str);
    if (!isNaN(n)) {
      str = n.toLocaleString('fullwide', { useGrouping: false });
    }
  }

  // Strip trailing .0 if integer stored as float
  if (str.endsWith('.0')) {
    str = str.slice(0, -2);
  }

  // Strip Excel formula equals sign (= or =" or =') and trailing quotes
  let cleaned = str.replace(/^=['"]?/, '').replace(/['"]$/, '');
  const hadPlus = cleaned.startsWith('+') || cleaned.startsWith('=+');

  // Strip all non-digit characters
  const digitsOnly = cleaned.replace(/\D/g, '');

  if (!digitsOnly || digitsOnly.length < 7 || digitsOnly.length > 15) {
    return '';
  }

  // If already had a plus, format with plus
  if (hadPlus) {
    return '+' + digitsOnly;
  }

  // Indian numbers starting with 91 (12 digits, e.g. 919876543210)
  if (digitsOnly.startsWith('91') && digitsOnly.length === 12) {
    return '+' + digitsOnly;
  }

  // Indian numbers starting with leading 0 (11 digits, e.g. 09876543210)
  if (digitsOnly.length === 11 && digitsOnly.startsWith('0') && /^[6-9]/.test(digitsOnly.slice(1))) {
    return '+91' + digitsOnly.slice(1);
  }

  // 10-digit number (default NANP +1)
  if (digitsOnly.length === 10) {
    return '+1' + digitsOnly;
  }

  // Other international numbers with country code without plus (11-15 digits)
  return '+' + digitsOnly;
}

/**
 * Validates an email address format
 */
export function validateEmail(email: string): boolean {
  if (!email) return false;
  return EMAIL_REGEX.test(normalizeEmail(email));
}

/**
 * Normalizes email address to lowercase
 */
export function normalizeEmail(email: any): string {
  if (email === null || email === undefined) return '';
  return String(email).trim().toLowerCase();
}

/**
 * Derives a human-readable contact name from an email address (e.g. john.doe@company.com -> John Doe)
 */
export function deriveNameFromEmail(email: string): string {
  if (!email || !email.includes('@')) return 'Contact';
  const prefix = email.split('@')[0];
  const cleaned = prefix.replace(/[._\-+0-9]+/g, ' ').trim();
  if (!cleaned) return 'Contact';
  return cleaned
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');
}

/**
 * Validates a single row of imported contact data
 */
export function validateContactRow(
  name: string,
  email: string,
  phone: string,
  company?: string,
  tagsRaw?: string,
  options: { allowPhoneOnly?: boolean } = { allowPhoneOnly: true }
): {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  cleanName: string;
  cleanEmail: string;
  cleanPhone: string;
  parsedTags: string[];
  isPhoneOnly: boolean;
} {
  const errors: string[] = [];
  const warnings: string[] = [];

  let cleanName = (name || '').trim();
  let cleanEmail = normalizeEmail(email);
  const cleanPhone = normalizePhone(phone);
  let isPhoneOnly = false;

  // Handle email validation
  if (!cleanEmail) {
    if (options.allowPhoneOnly && cleanPhone) {
      // Allow phone-only contact for WhatsApp/SMS campaigns.
      // Generate a valid placeholder email so Firestore rules (`data.email is string && data.email.size() > 3`) accept it.
      const phoneDigits = cleanPhone.replace(/\D/g, '');
      cleanEmail = `${phoneDigits}@contact.local`;
      isPhoneOnly = true;
      warnings.push('Phone-only contact: temporary email assigned for WhatsApp/SMS campaigns');
    } else {
      errors.push('Email is required');
    }
  } else if (!EMAIL_REGEX.test(cleanEmail)) {
    errors.push(`Invalid email format: "${cleanEmail}"`);
  } else if (cleanEmail.length > 200) {
    errors.push('Email must not exceed 200 characters');
  }

  // Handle name validation
  if (!cleanName) {
    if (cleanEmail && !isPhoneOnly) {
      cleanName = deriveNameFromEmail(cleanEmail);
      warnings.push(`Name auto-derived from email: "${cleanName}"`);
    } else if (cleanPhone) {
      cleanName = `Contact (${cleanPhone})`;
      warnings.push('Name missing: generated contact label from phone number');
    } else if (company && company.trim()) {
      cleanName = company.trim();
    } else {
      errors.push('Contact Name is required');
    }
  } else if (cleanName.length > 150) {
    cleanName = cleanName.slice(0, 150);
    warnings.push('Name truncated to 150 characters');
  }

  // Validate phone format if phone is provided
  if (phone && String(phone).trim() && !cleanPhone) {
    warnings.push(`Unrecognized phone number format: "${String(phone).trim()}"`);
  }

  const parsedTags: string[] = [];
  if (isPhoneOnly) {
    parsedTags.push('phone-only');
  }
  if (tagsRaw) {
    const rawList = String(tagsRaw).split(/[,;|]/);
    for (const tag of rawList) {
      const trimmed = tag.trim();
      if (trimmed && !parsedTags.includes(trimmed)) {
        parsedTags.push(trimmed);
      }
    }
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
    cleanName,
    cleanEmail,
    cleanPhone,
    parsedTags,
    isPhoneOnly,
  };
}

/**
 * Intelligent helper to score a row for contact header keywords
 */
function scoreRowForHeaders(row: any[]): number {
  let score = 0;
  for (const cell of row) {
    const c = String(cell || '').trim().toLowerCase().replace(/[^a-z0-9]/g, '');
    if (!c) continue;

    if (['name', 'fullname', 'contactname', 'clientname', 'customername'].includes(c)) score += 3;
    else if (['firstname', 'fname', 'lastname', 'lname'].includes(c)) score += 2;
    else if (['email', 'emailaddress', 'mail', 'emailid', 'mailid'].includes(c)) score += 3;
    else if (['phone', 'phonenumber', 'mobile', 'mobilenumber', 'mobileno', 'phoneno', 'whatsapp', 'cell'].includes(c)) score += 3;
    else if (['company', 'companyname', 'organization', 'organisation', 'org', 'business'].includes(c)) score += 2;
    else if (['tags', 'tag', 'category', 'group', 'label', 'status'].includes(c)) score += 1;
    else if (c.includes('name') || c.includes('email') || c.includes('phone') || c.includes('mobile')) score += 1;
  }
  return score;
}

/**
 * Parses an uploaded Excel (.xlsx, .xls, .csv, .tsv, .xlsm, .ods) file buffer or ArrayBuffer
 * with ultra-fast raw cell reading, safe bounds clamping, multi-sheet selection, and interactive column mapping.
 */
export async function parseExcelFile(
  fileData: ArrayBuffer | Uint8Array,
  existingContacts: Contact[] = [],
  options: ParseExcelOptions = {}
): Promise<ParseExcelResult> {
  // Read workbook fast with dense mode, cellDates false to prevent expensive formatting on each cell
  const workbook = XLSX.read(fileData, {
    type: 'array',
    cellDates: false,
    dense: true,
  });

  const availableSheets = workbook.SheetNames || [];
  if (availableSheets.length === 0) {
    throw new Error('The uploaded file contains no sheets or readable data.');
  }

  // Select target sheet
  let activeSheetName = options.sheetName || '';
  let activeSheet: XLSX.WorkSheet | null = null;

  if (activeSheetName && workbook.Sheets[activeSheetName]) {
    activeSheet = workbook.Sheets[activeSheetName];
  } else {
    // Score all sheets to automatically find the one with contact headers
    let bestScore = -1;
    let bestSheetName = availableSheets[0];

    for (const sName of availableSheets) {
      const s = workbook.Sheets[sName];
      if (!s || !s['!ref']) continue;

      const previewGrid: any[][] = XLSX.utils.sheet_to_json(s, {
        header: 1,
        defval: '',
        raw: true,
        blankrows: false,
      });

      if (!previewGrid || previewGrid.length === 0) continue;

      let sheetScore = 0;
      for (let r = 0; r < Math.min(previewGrid.length, 10); r++) {
        sheetScore += scoreRowForHeaders(previewGrid[r] || []);
      }

      if (sheetScore > bestScore) {
        bestScore = sheetScore;
        bestSheetName = sName;
      }
    }

    activeSheetName = bestSheetName;
    activeSheet = workbook.Sheets[activeSheetName];
  }

  if (!activeSheet || !activeSheet['!ref']) {
    throw new Error(`Worksheet "${activeSheetName}" is empty or has no readable range.`);
  }

  // Safety Clamp: In Excel, if someone selected an entire column, range.e.r can be 1,048,576!
  // Clamping prevents out-of-memory or 30-second main-thread browser freezes.
  try {
    const range = XLSX.utils.decode_range(activeSheet['!ref']);
    if (range.e.r - range.s.r > 25000) {
      range.e.r = Math.min(range.e.r, range.s.r + 25000);
      activeSheet['!ref'] = XLSX.utils.encode_range(range);
    }
  } catch {
    // Continue with existing ref if decode fails
  }

  // Convert to 2D array of rows fast
  const rawRowsGrid: any[][] = XLSX.utils.sheet_to_json(activeSheet, {
    header: 1,
    defval: '',
    raw: true,
    blankrows: false,
  });

  if (!rawRowsGrid || rawRowsGrid.length === 0) {
    throw new Error('The worksheet contains no data rows.');
  }

  // Determine header row index
  let bestHeaderRowIndex = typeof options.headerRowIndex === 'number' ? options.headerRowIndex : 0;
  if (typeof options.headerRowIndex !== 'number') {
    let maxScore = -1;
    for (let r = 0; r < Math.min(rawRowsGrid.length, 20); r++) {
      const score = scoreRowForHeaders(rawRowsGrid[r] || []);
      if (score > maxScore) {
        maxScore = score;
        bestHeaderRowIndex = r;
      }
    }
  }

  const rawHeaderRow = rawRowsGrid[bestHeaderRowIndex] || [];
  const headerStrings = rawHeaderRow.map((h, i) => {
    const val = String(h ?? '').trim();
    return val || `Column ${i + 1}`;
  });

  // Build available columns list for UI mapping
  const sampleRow = rawRowsGrid[bestHeaderRowIndex + 1] || [];
  const availableColumns: AvailableColumn[] = headerStrings.map((label, idx) => ({
    index: idx,
    label,
    sample: sampleRow[idx] !== undefined ? String(sampleRow[idx]).trim().slice(0, 40) : '',
  }));

  // Auto-detect column mapping unless explicitly provided
  let nameCol = options.columnMapping?.nameCol ?? -1;
  let firstNameCol = options.columnMapping?.firstNameCol ?? -1;
  let lastNameCol = options.columnMapping?.lastNameCol ?? -1;
  let emailCol = options.columnMapping?.emailCol ?? -1;
  let phoneCol = options.columnMapping?.phoneCol ?? -1;
  let companyCol = options.columnMapping?.companyCol ?? -1;
  let tagsCol = options.columnMapping?.tagsCol ?? -1;

  // Auto-detection logic if not explicitly mapped
  headerStrings.forEach((header, idx) => {
    const norm = header.toLowerCase().replace(/[^a-z0-9]/g, '');

    // Name detection
    if (nameCol === -1) {
      if (['name', 'fullname', 'contactname', 'clientname', 'customername', 'user', 'username', 'leadname', 'person'].includes(norm)) {
        nameCol = idx;
      }
    }
    if (firstNameCol === -1 && ['firstname', 'fname', 'givenname', 'first'].includes(norm)) {
      firstNameCol = idx;
    }
    if (lastNameCol === -1 && ['lastname', 'lname', 'surname', 'familyname', 'last'].includes(norm)) {
      lastNameCol = idx;
    }

    // Email detection
    if (emailCol === -1) {
      if (
        [
          'email',
          'emailaddress',
          'mail',
          'emailid',
          'mailid',
          'primaryemail',
          'useremail',
          'clientemail',
          'contactemail',
          'workemail',
          'personalemail',
        ].includes(norm)
      ) {
        emailCol = idx;
      }
    }

    // Phone detection
    if (phoneCol === -1) {
      if (
        [
          'phone',
          'phonenumber',
          'mobile',
          'mobilenumber',
          'mobileno',
          'phoneno',
          'cell',
          'cellphone',
          'whatsapp',
          'whatsappnumber',
          'contactno',
          'contactnumber',
          'telephone',
          'phno',
          'mob',
        ].includes(norm)
      ) {
        phoneCol = idx;
      }
    }

    // Company detection
    if (companyCol === -1) {
      if (
        [
          'company',
          'companyname',
          'organization',
          'organisation',
          'organizationname',
          'business',
          'businessname',
          'account',
          'employer',
          'firm',
          'firmname',
          'agency',
        ].includes(norm)
      ) {
        companyCol = idx;
      }
    }

    // Tags detection
    if (tagsCol === -1) {
      if (
        [
          'tags',
          'tag',
          'category',
          'categories',
          'group',
          'groups',
          'labels',
          'label',
          'segment',
          'list',
        ].includes(norm)
      ) {
        tagsCol = idx;
      }
    }
  });

  // Secondary loose detection if still unmapped
  if (nameCol === -1 && firstNameCol === -1) {
    nameCol = headerStrings.findIndex((h) => {
      const l = h.toLowerCase();
      return l.includes('name') && !l.includes('company') && !l.includes('account');
    });
  }
  if (emailCol === -1) {
    emailCol = headerStrings.findIndex((h) => {
      const l = h.toLowerCase();
      return l.includes('email') || l.includes('mail');
    });
  }
  if (phoneCol === -1) {
    phoneCol = headerStrings.findIndex((h) => {
      const l = h.toLowerCase();
      return l.includes('phone') || l.includes('mobile') || l.includes('cell') || l.includes('whatsapp');
    });
  }
  if (companyCol === -1) {
    companyCol = headerStrings.findIndex((h) => {
      const l = h.toLowerCase();
      return l.includes('company') || l.includes('org') || l.includes('business') || l.includes('firm');
    });
  }

  // Pre-index existing contacts for instant duplicate detection
  const existingEmailSet = new Set(existingContacts.map((c) => normalizeEmail(c.email)).filter(Boolean));
  const existingPhoneSet = new Set(existingContacts.map((c) => normalizePhone(c.phone)).filter(Boolean));

  const seenEmailsInFile = new Map<string, number>();
  const seenPhonesInFile = new Map<string, number>();

  const records: ValidatedImportRecord[] = [];
  let validCount = 0;
  let invalidCount = 0;
  let duplicateCount = 0;
  let existingDuplicateCount = 0;
  let phoneOnlyCount = 0;

  for (let i = bestHeaderRowIndex + 1; i < rawRowsGrid.length; i++) {
    const row = rawRowsGrid[i] || [];
    const rowIndex = i + 1;

    const getVal = (col: number) => {
      if (col < 0 || col >= row.length) return '';
      const v = row[col];
      if (v === null || v === undefined) return '';
      return String(v).trim();
    };

    let rawName = getVal(nameCol);
    if (!rawName && (firstNameCol >= 0 || lastNameCol >= 0)) {
      rawName = [getVal(firstNameCol), getVal(lastNameCol)].filter(Boolean).join(' ').trim();
    }

    const rawEmail = getVal(emailCol);
    const rawPhone = getVal(phoneCol);
    const rawCompany = getVal(companyCol);
    const rawTags = getVal(tagsCol);

    // Skip entirely empty row
    if (!rawName && !rawEmail && !rawPhone && !rawCompany) {
      continue;
    }

    const {
      isValid: basicValid,
      errors,
      warnings,
      cleanName,
      cleanEmail,
      cleanPhone,
      parsedTags,
      isPhoneOnly,
    } = validateContactRow(rawName, rawEmail, rawPhone, rawCompany, rawTags, {
      allowPhoneOnly: options.allowPhoneOnly !== false,
    });

    if (isPhoneOnly) {
      phoneOnlyCount++;
    }

    let isDuplicateInFile = false;
    let isExistingInDb = false;

    // Check duplicate email in this file
    if (cleanEmail && !isPhoneOnly) {
      if (seenEmailsInFile.has(cleanEmail)) {
        errors.push(`Duplicate email in file (first seen on row ${seenEmailsInFile.get(cleanEmail)})`);
        isDuplicateInFile = true;
      } else {
        seenEmailsInFile.set(cleanEmail, rowIndex);
      }
    }

    // Check duplicate phone in this file
    if (cleanPhone) {
      if (seenPhonesInFile.has(cleanPhone)) {
        errors.push(`Duplicate phone in file (first seen on row ${seenPhonesInFile.get(cleanPhone)})`);
        isDuplicateInFile = true;
      } else {
        seenPhonesInFile.set(cleanPhone, rowIndex);
      }
    }

    // Check against existing database
    if (cleanEmail && existingEmailSet.has(cleanEmail)) {
      errors.push('Email already exists in Contacts database');
      isExistingInDb = true;
    } else if (isPhoneOnly && cleanPhone && existingPhoneSet.has(cleanPhone)) {
      errors.push('Phone already exists in Contacts database');
      isExistingInDb = true;
    }

    if (isDuplicateInFile) duplicateCount++;
    if (isExistingInDb) existingDuplicateCount++;

    const finalIsValid = basicValid && !isDuplicateInFile && !isExistingInDb;

    if (finalIsValid) {
      validCount++;
    } else {
      invalidCount++;
    }

    records.push({
      rowIndex,
      data: {
        name: cleanName,
        email: cleanEmail,
        phone: cleanPhone || rawPhone,
        company: rawCompany,
        tags: parsedTags,
      },
      isValid: finalIsValid,
      errors,
      warnings,
      isPhoneOnly,
      isDuplicateInFile,
      isExistingInDb,
    });
  }

  return {
    records,
    validCount,
    invalidCount,
    duplicateCount,
    existingDuplicateCount,
    phoneOnlyCount,
    availableSheets,
    activeSheetName,
    headerRowIndex: bestHeaderRowIndex,
    availableColumns,
    mappedColumns: {
      nameCol,
      emailCol,
      phoneCol,
      companyCol,
      tagsCol,
    },
    totalRawRows: rawRowsGrid.length,
  };
}

/**
 * Creates and downloads a starter sample Excel file with correct headers and dummy data
 */
export function downloadSampleExcelTemplate(): void {
  const sampleData = [
    {
      Name: 'Sarah Jenkins',
      Email: 'sarah.jenkins@acmecorp.com',
      Phone: '+14155552671',
      Company: 'Acme Corp',
      Tags: 'VIP, Enterprise, Monthly Newsletter',
    },
    {
      Name: 'Marcus Vance',
      Email: 'marcus.v@innovatetech.io',
      Phone: '+12125558902',
      Company: 'InnovateTech',
      Tags: 'Prospect, Product Updates',
    },
    {
      Name: 'Priya Sharma',
      Email: 'priya.sharma@techindia.in',
      Phone: '+919876543210',
      Company: 'Tech India',
      Tags: 'Client, WhatsApp Opt-in',
    },
    {
      Name: 'Rohan Mehta',
      Email: '',
      Phone: '+919812345678',
      Company: 'Mehta Logistics',
      Tags: 'WhatsApp Only, Regional',
    },
    {
      Name: 'David Chen',
      Email: 'david.chen@apexretail.org',
      Phone: '+16505553412',
      Company: 'Apex Retail',
      Tags: 'Retail, SMS Subscriber',
    },
  ];

  const worksheet = XLSX.utils.json_to_sheet(sampleData);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Contacts');
  XLSX.writeFile(workbook, 'contacts_import_template.xlsx');
}

/**
 * Creates and downloads a starter sample CSV file
 */
export function downloadSampleCsvTemplate(): void {
  const csvContent =
    'Name,Email,Phone,Company,Tags\r\n' +
    'Sarah Jenkins,sarah.jenkins@acmecorp.com,+14155552671,Acme Corp,"VIP, Monthly Newsletter"\r\n' +
    'Marcus Vance,marcus.v@innovatetech.io,+12125558902,InnovateTech,"Prospect, Updates"\r\n' +
    'Priya Sharma,priya.sharma@techindia.in,+919876543210,Tech India,"Client, WhatsApp"\r\n' +
    'Rohan Mehta,,+919812345678,Mehta Logistics,"WhatsApp Only"\r\n' +
    'David Chen,david.chen@apexretail.org,,Apex Retail,"Email Only, Newsletter"\r\n';

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', 'contacts_import_template.csv');
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Export contacts list to an Excel file
 */
export function exportContactsToExcel(contacts: Contact[], fileName = 'contacts_export.xlsx'): void {
  const rows = contacts.map((c) => ({
    Name: c.name,
    Email: c.email.includes('@contact.local') ? '' : c.email,
    Phone: c.phone,
    Company: c.company || '',
    Tags: c.tags.join(', '),
    Status: c.status,
    Consent: c.consentGiven ? 'Yes' : 'No',
    Created: c.createdAt ? new Date(c.createdAt).toLocaleDateString() : '',
  }));

  const worksheet = XLSX.utils.json_to_sheet(rows);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Contacts');
  XLSX.writeFile(workbook, fileName);
}
